apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/nginx/deployment.yaml
  - k8s/nginx/service.yaml

commonLabels:
  app: nginx
  managed-by: argocd

namespace: default
